// js/data.js - Industries & Factor Meta - v61.3 100% REAL KRX + 15007 CSV REAL + DART + Regime (구리+상해)
// 분리된 데이터 파일 - 베타 수정 시 여기만 수정

var industries = [
        {
          id: "elec",
          name: "전기전자/반도체",
          short: "전기전자",
          icon: "◫",
          r2: 0.91,
          color: "#2563eb",
          grad: "grad-elec",
          betas: {
            "S&P500": 0.42,
            "외국인 선물": 0.28,
            "SOX / 필라": 0.35,
            "US 10Y": -0.18,
            구리: 0.15,
            상해종합: 0.10,
            DXY: -0.08,
            VIX: -0.06,
          },
          desc: "나스닥/외국인 + 중국 프록시(구리/상해) 민감",
        },
        {
          id: "auto",
          name: "자동차/운수장비",
          short: "자동차",
          icon: "◩",
          r2: 0.84,
          color: "#0f766e",
          grad: "grad-auto",
          betas: {
            원달러: 0.25,
            WTI: -0.15,
            "S&P500": 0.20,
            구리: 0.12,
            상해종합: 0.14,
            DXY: 0.10,
          },
          desc: "환율/유가 + 중국 수요(구리/상해) 민감 수출주",
        },
        {
          id: "chem",
          name: "화학/2차전지",
          short: "화학·전지",
          icon: "⬡",
          r2: 0.79,
          color: "#9333ea",
          grad: "grad-chem",
          betas: {
            구리: 0.32,
            상해종합: 0.22,
            WTI: -0.18,
            원달러: -0.10,
            "S&P500": 0.12,
          },
          desc: "중국 경기 대리변수 구리/상해에 가장 민감",
        },
        {
          id: "fin",
          name: "금융/증권",
          short: "금융",
          icon: "₩",
          r2: 0.87,
          color: "#1e293b",
          grad: "grad-fin",
          betas: {
            "US 10Y": -0.30,
            DXY: 0.18,
            "외국인 선물": 0.15,
            VIX: -0.15,
            "S&P500": 0.10,
          },
          desc: "금리 + 달러 + VIX 민감, 중국 프록시 간접",
        },
        {
          id: "bio",
          name: "바이오/의약품",
          short: "바이오",
          icon: "⚕",
          r2: 0.71,
          color: "#e11d48",
          grad: "grad-bio",
          betas: {
            "US 10Y": -0.22,
            "S&P500": 0.18,
            VIX: -0.18,
            DXY: -0.06,
          },
          desc: "금리 하락/ VIX 하락 수혜",
        },
        {
          id: "steel",
          name: "철강/소재/에너지",
          short: "철강·소재",
          icon: "⬣",
          r2: 0.84,
          color: "#a16207",
          grad: "grad-steel",
          betas: { 구리: 0.35, 상해종합: 0.28, 원달러: 0.15, WTI: 0.14, "S&P500": 0.08, DXY: 0.10 },
          desc: "구리/상해종합 - 중국 경기 직결",
        },
        {
          id: "const",
          name: "건설/조선/기계",
          short: "건설·조선",
          icon: "⌖",
          r2: 0.76,
          color: "#334155",
          grad: "grad-const",
          betas: {
            구리: 0.22,
            상해종합: 0.18,
            원달러: 0.15,
            WTI: 0.08,
            DXY: 0.08,
          },
          desc: "중국 인프라 수요 = 구리/상해종합",
        },
        {
          id: "retail",
          name: "유통/IT서비스",
          short: "유통·IT",
          icon: "◎",
          r2: 0.80,
          color: "#0891b2",
          grad: "grad-retail",
          betas: {
            "S&P500": 0.22,
            "외국인 선물": 0.18,
            상해종합: 0.12,
            구리: 0.08,
            VIX: -0.10,
          },
          desc: "내수+플랫폼 + 중국 소비 심리",
        },
      ];

var factorMeta = {
        "S&P500": { label: "S&P500", desc: "전일 수익률 Z" },
        "외국인 선물": { label: "외국인 선물", desc: "KOSPI200 선물 순매수" },
        "SOX / 필라": { label: "SOX / 필라", desc: "반도체 지수 모멘텀" },
        "US 10Y": { label: "US 10Y", desc: "금리 변동 Z" },
        원달러: { label: "원/달러", desc: "환율 변동 Z" },
        WTI: { label: "WTI", desc: "유가 변동 Z" },
        DXY: { label: "DXY", desc: "달러 인덱스 Z" },
        VIX: { label: "VIX", desc: "변동성 지수 Z" },
        구리: { label: "구리", desc: "China Proxy 1 - 경기민감 REAL" },
        상해종합: { label: "상해종합", desc: "China Proxy 2 - SSE REAL" },
        외국인: { label: "외국인 선물", desc: "외국인 수급" },
        반도체팩터: { label: "SOX / 필라", desc: "반도체 모멘텀" },
        SP500: { label: "S&P500", desc: "전일 수익률" },
      };
